FROM ollama/ollama:latest

RUN apt-get update && apt-get install -y ca-certificates curl && rm -rf /var/lib/apt/lists/*

ENV OLLAMA_INSECURE=1
RUN (ollama serve &) && \
    sleep 5 && \
    ollama pull nomic-embed-text