# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/sanitizer.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15proto/sanitizer.proto\x12\tsanitizer\"?\n\x0fSanitizeRequest\x12\x15\n\rdocument_type\x18\x01 \x01(\t\x12\x15\n\rdocument_data\x18\x02 \x01(\x0c\"-\n\x10SanitizeResponse\x12\x19\n\x11sanitized_content\x18\x01 \x01(\t2_\n\x10SanitizerService\x12K\n\x10SanitizeDocument\x12\x1a.sanitizer.SanitizeRequest\x1a\x1b.sanitizer.SanitizeResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.sanitizer_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SANITIZEREQUEST']._serialized_start=36
  _globals['_SANITIZEREQUEST']._serialized_end=99
  _globals['_SANITIZERESPONSE']._serialized_start=101
  _globals['_SANITIZERESPONSE']._serialized_end=146
  _globals['_SANITIZERSERVICE']._serialized_start=148
  _globals['_SANITIZERSERVICE']._serialized_end=243
# @@protoc_insertion_point(module_scope)
