# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import sanitizer_pb2 as proto_dot_sanitizer__pb2


class SanitizerServiceStub(object):
    """Defines the service contract for sanitizing documents.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SanitizeDocument = channel.unary_unary(
                '/sanitizer.SanitizerService/SanitizeDocument',
                request_serializer=proto_dot_sanitizer__pb2.SanitizeRequest.SerializeToString,
                response_deserializer=proto_dot_sanitizer__pb2.SanitizeResponse.FromString,
                )


class SanitizerServiceServicer(object):
    """Defines the service contract for sanitizing documents.
    """

    def SanitizeDocument(self, request, context):
        """A RPC to sanitize a document.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SanitizerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SanitizeDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.SanitizeDocument,
                    request_deserializer=proto_dot_sanitizer__pb2.SanitizeRequest.FromString,
                    response_serializer=proto_dot_sanitizer__pb2.SanitizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sanitizer.SanitizerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SanitizerService(object):
    """Defines the service contract for sanitizing documents.
    """

    @staticmethod
    def SanitizeDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/sanitizer.SanitizerService/SanitizeDocument',
            proto_dot_sanitizer__pb2.SanitizeRequest.SerializeToString,
            proto_dot_sanitizer__pb2.SanitizeResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
