/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 3.19.1
 * source: sanitizer.proto
 * git: https:/github.com/thesayyn/protoc-gen-ts */
import * as pb_1 from "google-protobuf";
import * as grpc_1 from "@grpc/grpc-js";
export namespace sanitizer {
    export class SanitizeRequest extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            document_type?: string;
            document_data?: Uint8Array;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("document_type" in data && data.document_type != undefined) {
                    this.document_type = data.document_type;
                }
                if ("document_data" in data && data.document_data != undefined) {
                    this.document_data = data.document_data;
                }
            }
        }
        get document_type() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set document_type(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        get document_data() {
            return pb_1.Message.getFieldWithDefault(this, 2, new Uint8Array(0)) as Uint8Array;
        }
        set document_data(value: Uint8Array) {
            pb_1.Message.setField(this, 2, value);
        }
        static fromObject(data: {
            document_type?: string;
            document_data?: Uint8Array;
        }): SanitizeRequest {
            const message = new SanitizeRequest({});
            if (data.document_type != null) {
                message.document_type = data.document_type;
            }
            if (data.document_data != null) {
                message.document_data = data.document_data;
            }
            return message;
        }
        toObject() {
            const data: {
                document_type?: string;
                document_data?: Uint8Array;
            } = {};
            if (this.document_type != null) {
                data.document_type = this.document_type;
            }
            if (this.document_data != null) {
                data.document_data = this.document_data;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.document_type.length)
                writer.writeString(1, this.document_type);
            if (this.document_data.length)
                writer.writeBytes(2, this.document_data);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SanitizeRequest {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SanitizeRequest();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.document_type = reader.readString();
                        break;
                    case 2:
                        message.document_data = reader.readBytes();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SanitizeRequest {
            return SanitizeRequest.deserialize(bytes);
        }
    }
    export class SanitizeResponse extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            sanitized_content?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("sanitized_content" in data && data.sanitized_content != undefined) {
                    this.sanitized_content = data.sanitized_content;
                }
            }
        }
        get sanitized_content() {
            return pb_1.Message.getFieldWithDefault(this, 1, "") as string;
        }
        set sanitized_content(value: string) {
            pb_1.Message.setField(this, 1, value);
        }
        static fromObject(data: {
            sanitized_content?: string;
        }): SanitizeResponse {
            const message = new SanitizeResponse({});
            if (data.sanitized_content != null) {
                message.sanitized_content = data.sanitized_content;
            }
            return message;
        }
        toObject() {
            const data: {
                sanitized_content?: string;
            } = {};
            if (this.sanitized_content != null) {
                data.sanitized_content = this.sanitized_content;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.sanitized_content.length)
                writer.writeString(1, this.sanitized_content);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): SanitizeResponse {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new SanitizeResponse();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.sanitized_content = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): SanitizeResponse {
            return SanitizeResponse.deserialize(bytes);
        }
    }
    interface GrpcUnaryServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
        (message: P, callback: grpc_1.requestCallback<R>): grpc_1.ClientUnaryCall;
    }
    interface GrpcStreamServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
        (message: P, options?: grpc_1.CallOptions): grpc_1.ClientReadableStream<R>;
    }
    interface GrpWritableServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (metadata: grpc_1.Metadata, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (options: grpc_1.CallOptions, callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
        (callback: grpc_1.requestCallback<R>): grpc_1.ClientWritableStream<P>;
    }
    interface GrpcChunkServiceInterface<P, R> {
        (metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
        (options?: grpc_1.CallOptions): grpc_1.ClientDuplexStream<P, R>;
    }
    interface GrpcPromiseServiceInterface<P, R> {
        (message: P, metadata: grpc_1.Metadata, options?: grpc_1.CallOptions): Promise<R>;
        (message: P, options?: grpc_1.CallOptions): Promise<R>;
    }
    export abstract class UnimplementedSanitizerServiceService {
        static definition = {
            SanitizeDocument: {
                path: "/sanitizer.SanitizerService/SanitizeDocument",
                requestStream: false,
                responseStream: false,
                requestSerialize: (message: SanitizeRequest) => Buffer.from(message.serialize()),
                requestDeserialize: (bytes: Buffer) => SanitizeRequest.deserialize(new Uint8Array(bytes)),
                responseSerialize: (message: SanitizeResponse) => Buffer.from(message.serialize()),
                responseDeserialize: (bytes: Buffer) => SanitizeResponse.deserialize(new Uint8Array(bytes))
            }
        };
        [method: string]: grpc_1.UntypedHandleCall;
        abstract SanitizeDocument(call: grpc_1.ServerUnaryCall<SanitizeRequest, SanitizeResponse>, callback: grpc_1.sendUnaryData<SanitizeResponse>): void;
    }
    export class SanitizerServiceClient extends grpc_1.makeGenericClientConstructor(UnimplementedSanitizerServiceService.definition, "SanitizerService", {}) {
        constructor(address: string, credentials: grpc_1.ChannelCredentials, options?: Partial<grpc_1.ChannelOptions>) {
            super(address, credentials, options);
        }
        SanitizeDocument: GrpcUnaryServiceInterface<SanitizeRequest, SanitizeResponse> = (message: SanitizeRequest, metadata: grpc_1.Metadata | grpc_1.CallOptions | grpc_1.requestCallback<SanitizeResponse>, options?: grpc_1.CallOptions | grpc_1.requestCallback<SanitizeResponse>, callback?: grpc_1.requestCallback<SanitizeResponse>): grpc_1.ClientUnaryCall => {
            return super.SanitizeDocument(message, metadata, options, callback);
        };
    }
}
