name: Test Pipeline

on:
  pull_request:
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:6
        ports:
          - 6379:6379
      postgres:
        image: postgres:14
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run linter
        run: npm run lint

      - name: Run type check
        run: npm run type-check

      - name: Run type check
        run: npm run type-check

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install -r python_service/requirements.txt

      - name: Start gRPC sanitizer (background)
        run: |
          python python_service/main_grpc_server.py &
          for i in {1..60}; do
            (echo > /dev/tcp/127.0.0.1/50051) >/dev/null 2>&1 && break
            sleep 1
          done

      - name: Run tests
        env:
          NODE_ENV: test
          POSTGRES_URL: postgres://postgres:postgres@localhost:5432/testdb
          REDIS_URL: redis://localhost:6379
          JWT_SECRET: test-secret
          SANITIZER_HOST: 127.0.0.1:50051
          HUGGINGFACE_HUB_TOKEN: ${{ secrets.HUGGINGFACE_HUB_TOKEN }}
          PINECONE_API_KEY: ${{ secrets.PINECONE_API_KEY }}
          HUGGINGFACE_CHAT_MODEL: ${{ secrets.HUGGINGFACE_CHAT_MODEL }}
          HUGGINGFACE_SUMMARY_MODEL: ${{ secrets.HUGGINGFACE_SUMMARY_MODEL }}
          HUGGINGFACE_EMBEDDING_MODEL: ${{ secrets.HUGGINGFACE_EMBEDDING_MODEL }}
        run: npm test

      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
